sudo: false
group: edge

language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

os:
  - linux
  - osx

before_install:
  - uname -a
  - sudo apt-get update
  - sudo apt-get install libphash0 libphash-dev

script:
  - go test -v ./...
  - go test -v -benchmem -benchtime=5s -bench=.

matrix:
  allow_failures:
    - go: 1.5
    - go: tip
